services:
  app1:
    build:
      context: ./app1
    ports:
      - "3001:80"
    container_name: ns8-app1
    restart: unless-stopped
  app2:
    build:
      context: ./app2
    ports:
      - "3002:80"
    container_name: ns8-app2
    restart: unless-stopped
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
    container_name: revproxy
    restart: unless-stopped
